### ISSUE TITLE
[Web] sentry.io changed domain, need to update CSP

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-web#2633]
![image](https://user-images.githubusercontent.com/49659410/181628960-fdb59237-8e92-4d5d-9b37-e61049e854c7.png)

**Comment by tx0c** [comment]
might just need `*.sentry.io` ?

**Comment by Carolusian** [comment]
check if there is potential risk similar to slope

**Comment by robertu7** [comment]
> check if there is potential risk similar to slope

https://mattersnews.slack.com/archives/C88CK7Q7L/p1659590919766839 @Carolusian

**Comment by Carolusian** [comment]
@devformatters @robertu7 Since we don't store private key information, it is highly unlikely to have private key information being leaked to Sentry. But we still need to pay attention to other kinds of sensitivity information. 

In Sentry project setting, there  is  a `Data Scrubbing` option which has been enabled for all projects by default. The following data is being scrubbed by default:

- Values that look like they contain credit cards (using a basic regular expression)
- Values that themselves contain, or whose keynames contain, any of the following strings:
  - password
  - secret
  - passwd
  - api_key
  - apikey
  - access_token
  - auth
  - credentials
  - mysql_pwd
  - stripetoken
  - card[number]
  - github_token
  - privatekey
  - private_key
- Other information set in `Additional Sensitive Fields`

In addition, data can also be scrubbed in `beforeSend` hook.

See: 
- https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/
- https://docs.sentry.io/platforms/javascript/data-management/sensitive-data/
