### ISSUE TITLE
[Web] Thumbnails are not showed in the first page view on mobile device

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2751]
### Tasks
- [ ] Investigate and fix the problem

### Screenshots

<img width="55%" alt="screen shot" src="https://user-images.githubusercontent.com/34237112/188599162-c4fc37f1-a66e-4c2e-96eb-8b3a6fba09fa.jpeg">

<img width="55%" alt="screen shot" src="https://user-images.githubusercontent.com/34237112/188598921-6e7a9048-ad04-4970-a57d-f7b218e355e0.jpeg">

**Comment by robertu7** [comment]
Possibly caused by Cloudflare's [Mirage](https://support.cloudflare.com/hc/en-us/articles/219178057-Configuring-Cloudflare-Mirage), which modifies the `<img>`, adds a custom lazy loading attribute `data-cfsrc`. 

This feature is turned off now and it works on my side:

![Image](https://user-images.githubusercontent.com/4065233/189859645-1312b372-cb1b-4df0-ac50-0a845abb0575.png)
